# Tutorial Numpy
Juan C. Zagal - Cristián Herrera

El objetivo de este notebook consiste en introducir y repasar la librería Numpy pues será extensamente utilizada a lo largo del curso.

Dado que la manipulación de matrices y arreglos numéricos resulta escencial en lo que respecta a procesamiento de datos, imágenes y visión computacional, Numpy se ha posicionado como una librería escencial a la hora de abordar proyectos de procesamiento y análisis numérico. De este modo es necesario poseer una buena base de esta librería y sus funcionalidades antes de seguir con proyectos de mayor complejidad.

## Documentación
Pueden revisar la documentación de Numpy en el siguiente link:
- https://numpy.org/doc/stable/



# Numpy

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/1024px-NumPy_logo_2020.svg.png" width="400">


Numpy provee de funcionalidades orientadas a la manipulación de arreglos multidimensionales. De este modo su objeto principal corresponde al arreglo multidimensional homogeneo `numpy.ndarray` o `numpy.array`. Los `numpy.array` consisten en tablas o matrices de elementos (del mismo tipo) que pueden ser indexados mediante tuplas de enteros. En numpy, las dimensiones son referenciadas como `axes`.

Comencemos por importar la librería.



In [1]:
import numpy as np

Existen varios métodos que permiten crear o inicializar `np.arrays`, cada uno con su respectiva funcionalidad.

In [2]:
# np.array: Crea un array a partir de la lista entregada.
# note que se interpreta que una lista de listas corresponde a un 2D-array.
# analogamente, un lista de listas de listas corresponde a un 3D-array.
a = np.array( [ [1.5, 9.1, 2.9], [5.0, 6.3, 3.2], [0.0, 2.8, 7.3] ])
print('np.array:\n', a)

# np.zeros: Crea un array de ceros a partir de las dimensiones entregadas.
# las dimensiones se entregan en tuplas (m, n) -> (rows, cols)
a = np.zeros( (3, 5) )
print('\nnp.zeros:\n', a)

# np.ones: Crea un array de unos a partir de las dimensiones entregadas.
a = np.ones( (3, 4) )
print('\nnp.ones:\n', a)

# np.linspace: Crea un array de num valores equiespaciados dentro del rango.
a = np.linspace( 0.0, 10.0, num=5 )
print('\nnp.linspace:\n', a)

# np.random.uniform: Crea un array de valores random a partir de una
# distribución uniforme.
a = np.random.uniform( 0.0, 10.0, (4, 4) )
print('\nnp.random.uniform:\n', a)

# np.random.normal: Crea un array de valores random a partir de una
# distribución normal.
a = np.random.normal( 0.0, 1.0, (5, 3) )
print('\nnp.random.normal:\n', a)


np.array:
 [[1.5 9.1 2.9]
 [5.  6.3 3.2]
 [0.  2.8 7.3]]

np.zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

np.ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

np.linspace:
 [ 0.   2.5  5.   7.5 10. ]

np.random.uniform:
 [[9.50350794 3.24252364 7.66505659 7.3945732 ]
 [2.61615371 0.18186377 4.3232634  4.60253059]
 [7.52722831 5.12266122 9.9167527  5.0361519 ]
 [1.23183188 5.20369845 6.97631396 3.54208677]]

np.random.normal:
 [[-0.05738492 -0.61443927 -0.61552394]
 [ 0.29553615 -0.49405691 -0.99951038]
 [ 0.48837051 -1.60501048  0.70120925]
 [ 1.362906    0.40651562 -0.44457444]
 [ 0.28175255  1.72036431  0.30510441]]


## Atributos
Como toda clase o objeto, los `np.array` contienen varios atributos que entregan información sobre el objeto, como sus dimensiones y el tipo de elementos que contiene.

In [3]:
a = np.random.normal( 0.0, 2.0, (5, 3, 7) )

# :size: entrega la cantidad de elementos contenidos en el array.
print('size:', a.size)

# :ndim: entrega la cantidad de dimensiones del array.
print('ndim:', a.ndim)

# :shape: entrega el tamaño de cada una de las dimensiones del array.
print('shape:', a.shape)

# :dtype: entrega el tipo/type de los elementos contenidos.
print('dtype:', a.dtype)


size: 105
ndim: 3
shape: (5, 3, 7)
dtype: float64


## Data Types
Si nos fijamos en el resultado del bloque anterior, podemos notar que el type o `dtype` del `np.array` corresponde a `float64`. No obstante, no siempre querremos trabajar con este tipo de valores. Numpy soporta una gran variedad de tipos numéricos: booleans (`bool`), enteros con signo (`int`), enteros sin signo (`uint`), valores punto flotante (`floats`), e incluso valores complejos (`complex`).

Para transformar el `dtype` de un `np.array` podemos emplear el método `np.array.astype` o usar el mismo `type` objetivo como una función.



In [4]:
# creamos un np.array de valores random float64
a = np.random.uniform( 0.0, 255.0, (5, 5) )
print('a:\n', a)
print('\na.dtype: ', a.dtype)

# transformamos el np.array a enteros sin signo de 8-bits (uint8)
# este es el formato más común para trabajar imágenes digitales
b = a.astype('uint8')
print("\na.astype('unit8'):\n", b)
print('\na.dtype: ', b.dtype)

# podemos lograr la misma operación mediante np.uint8
b = np.uint8(a)
print('\nnp.uint8(a):\n', b)
print('\na.dtype: ', b.dtype)

a:
 [[ 72.46146023 127.89144748 220.81835494 170.3185392   24.29354852]
 [ 30.44022934  52.01971766 218.66328009 150.873901   220.87024875]
 [ 48.65358199  99.22557491  25.46021183  36.72933047 178.33383664]
 [ 95.88340595 208.65313782 131.28469979 119.94388572 101.1574158 ]
 [204.37917489  12.94725246  52.63275958   7.39534283  52.41064431]]

a.dtype:  float64

a.astype('unit8'):
 [[ 72 127 220 170  24]
 [ 30  52 218 150 220]
 [ 48  99  25  36 178]
 [ 95 208 131 119 101]
 [204  12  52   7  52]]

a.dtype:  uint8

np.uint8(a):
 [[ 72 127 220 170  24]
 [ 30  52 218 150 220]
 [ 48  99  25  36 178]
 [ 95 208 131 119 101]
 [204  12  52   7  52]]

a.dtype:  uint8


## Indexing
Similar a como los elementos son indexados en objetos `list`, los elementos de un `np.array` pueden ser indexados especificando cada una de sus dimensiones entre corchetes.

In [5]:
a = np.random.uniform( 0.0, 100.0, (4, 6, 5) )

# elemento en la celda (2, 5, 1)
b = a[2, 5, 1]
print('a[2, 5, 1]: ', b)

# se puede acceder al último elemento en una dimensión mediante -1
b = a[2, -1, -1]
print('\na[2, 5, 4]: ', b)

# también es posible acceder a múltiples elementos en una única operación,
# como también seleccionar sub-array dentro de un array.

# start:stop accede a los elementos dentro del intervalo [start, stop)
b = a[0:3, 5, 4]
print('\na[0:3, 5, 4]: ', b)

# start: accede a los elementos desde start hasta el último elemento.
b = a[2:, 5, 4]
print('\na[2:, 5, 4]: ', b)

# :stop accede a los elementos desde el primer elemento hasta stop - 1.
b = a[:3, 5, 4]
print('\na[:3, 5, 4]: ', b)

# : accede a todos los elementos en esa dimensión.
b = a[:, :, 0]
print('\na[:, :, 0]:\n', b)


a[2, 5, 1]:  88.9780782997688

a[2, 5, 4]:  4.937608094471779

a[0:3, 5, 4]:  [11.84374107 80.62765719  4.93760809]

a[2:, 5, 4]:  [4.93760809 2.72390195]

a[:3, 5, 4]:  [11.84374107 80.62765719  4.93760809]

a[:, :, 0]:
 [[31.92208199 38.3875565  96.02468406 79.06196751 81.79428307 67.8920571 ]
 [37.9600017  28.45851639 62.98593701 97.80088708 33.31426394 83.46931967]
 [95.75333937 84.08780508 87.37425833  3.32328222 92.61094833 21.6298918 ]
 [21.71898621 65.63935525 91.75844791 48.7475408  37.84825944 53.26039009]]


## Concatenar
Concatenar consiste en combinar dos o más `np.array`, lo cual puede ser logrado mediante `np.concatenate`, `np.vstack`, `np.hstack` o `np.dstack`, dependiendo de la dimensión en la que se desee trabajar.

In [6]:
a = np.random.uniform( 0.0, 100.0, (5, 3) )
b = np.ones( (5, 3) )

# np.concatenate concatena una secuencia de arrays en el axis especificado.
c = np.concatenate( (a, b), axis=1 )
print('np.concatenate (axis=1):\n', c)

# np.vstack es equivalente a np.concatenate en axis=0 (row wise)
c = np.vstack( (a, b) )
print('\nnp.vstack:\n', c)

# np.hstack es equivalente a np.concatenate en axis=1 (col wise)
c = np.hstack( (a, b) )
print('\nnp.hstack:\n', c)

# np.dstack es equivalente a np.concatenate en axis=2 (3D wise)
c = np.dstack( (a, b) )
print('\nnp.dstack dimensions:\n', c.shape)



np.concatenate (axis=1):
 [[58.48675687 75.91216746 52.09677571  1.          1.          1.        ]
 [ 5.37596694  4.17246007 32.4475662   1.          1.          1.        ]
 [37.22956001 86.05386787  5.88094755  1.          1.          1.        ]
 [42.8460094  86.0922918  52.67665499  1.          1.          1.        ]
 [63.18037271 56.5322149  28.03910267  1.          1.          1.        ]]

np.vstack:
 [[58.48675687 75.91216746 52.09677571]
 [ 5.37596694  4.17246007 32.4475662 ]
 [37.22956001 86.05386787  5.88094755]
 [42.8460094  86.0922918  52.67665499]
 [63.18037271 56.5322149  28.03910267]
 [ 1.          1.          1.        ]
 [ 1.          1.          1.        ]
 [ 1.          1.          1.        ]
 [ 1.          1.          1.        ]
 [ 1.          1.          1.        ]]

np.hstack:
 [[58.48675687 75.91216746 52.09677571  1.          1.          1.        ]
 [ 5.37596694  4.17246007 32.4475662   1.          1.          1.        ]
 [37.22956001 86.05386787  5.88

## Reshape
Una de las funcionalidades más útiles de numpy es su capacidad de transformar y modificar el `shape` de un `np.array`. La forma más común de realizar esta operación es mediante `np.reshape`.

In [7]:
a = np.arange(1, 25)
print('a:\n', a)

# np.reshape recibe el array a transformar y una tupla de la nueva shape.
# la nueva forma debe ser compatible con la cantidad de elementos original.
b = np.reshape(a, (3, 8))
print('\nnp.reshape(a, (3, 3)):\n', b)

# en caso de querer inferir alguna de las nuevas dimensiones, se debe entregar
# un -1 en la dimensión correspondiente
b = np.reshape(a, (-1, 3, 2))
print('\nnp.reshape(a, (-1, 3, 2))[:, :, 0]:\n', b[:, :, 0])

# note que en el orden del reshape anterior, los elementos se van insertando
# siguiendo la última dimensión, y a medida que esta se completa, se sigue con
# la dimensión anterior.
# esto puede ser controlado mediante el parámetro 'order'.
b = np.reshape(a, (-1, 3, 2), order='F')
print("\nnp.reshape(a, (-1, 3, 2), order='F')[:, :, 0]:\n", b[:, :, 0])


a:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

np.reshape(a, (3, 3)):
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]

np.reshape(a, (-1, 3, 2))[:, :, 0]:
 [[ 1  3  5]
 [ 7  9 11]
 [13 15 17]
 [19 21 23]]

np.reshape(a, (-1, 3, 2), order='F')[:, :, 0]:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


En caso de requerir transformar un array a un array 1D, esto puede ser logrado mediante `np.ravel` o `flatten`.

In [8]:
a = np.arange(1, 10).reshape( (-1, 3) )
print('a:\n', a)

b = a.flatten()
print('\na.flatten():\n', b)

b = a.ravel()
print('\na.ravel():\n', b)

# note que los resultados anteriores son distintos a a.reshape( (1, 9) ), pues
# pues el shape de este último es (1, 9), mientras que a.flatten() es (9, ).
b = a.reshape( (1, 9) )
print('\na.reshape( (1, 9) ):\n', b)


a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

a.flatten():
 [1 2 3 4 5 6 7 8 9]

a.ravel():
 [1 2 3 4 5 6 7 8 9]

a.reshape( (1, 9) ):
 [[1 2 3 4 5 6 7 8 9]]
